### ISSUE TITLE
Halfspace Strain solution contains Nans

### ISSUE THREAD

**Issue by hvasbath** [tbenthompson/cutde#29]
The same as with the displacement solution. Fix was the same setting cosB to EPS in case of zero. However, I couldnt find a triangle configuration that raises in a test. Found the Nans in a more complex setup. So sending here only a PR no updated matlab test.
My complex setup works after that.

**Comment by tbenthompson** [comment]
Thanks!

**Comment by tbenthompson** [comment]
@hvasbath I'll push a new release of cutde this weekend now that these bugs are all fixed up. Hope it's working well for your problems now!

**Comment by hvasbath** [comment]
Sounds good! For now I haven't stumbled upon another issue. Fingers crossed it stays like this 😉. The forward model is working, now lets see how the inversion goes. Without cutde this would be impossible to do in reasonable runtime. Again thanks a lot for putting it together!

**Comment by tbenthompson** [comment]
And thank you for finding the bugs!

**Comment by tbenthompson** [comment]
Just a heads up that I pushed a new version to PyPI. The `pip install` should now use the new version. In a few hours, the conda package will be updated too - that happens almost automatically but has a bit of time delay.
